# Generated by Django 5.2.7 on 2025-10-27 06:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_privider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('long_description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('coords', models.JSONField(blank=True, default=dict)),
                ('address', models.TextField()),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('accessibility_notes', models.TextField(blank=True, null=True)),
                ('permits_info', models.TextField()),
                ('entry_fee', models.CharField(max_length=50)),
                ('suggested_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.privider')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_edits', to='places.place')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_edits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
