# Generated by Django 5.2.7 on 2025-12-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
    ]
