# Generated by Django 5.2.7 on 2025-12-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='gallery',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='place',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='place',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='place',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
    ]
