# Generated by Django 5.2.7 on 2025-12-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_gallery_place_image1_place_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
    ]
