# Generated by Django 5.2.7 on 2025-12-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_district_place_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='accomodation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='food',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='overnight_stay',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
