# Generated by Django 5.2.7 on 2025-12-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_accomodation_place_food_place_overnight_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='nearest_airport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='nearest_bus_stop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='nearest_railway_station',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
