# Generated by Django 5.2.7 on 2025-12-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_created_by'),
        ('users', '0006_alter_provider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.provider'),
        ),
    ]
