# Generated by Django 5.2.7 on 2025-10-25 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('about', models.CharField(blank=True, max_length=300, null=True)),
                ('services_offered', models.JSONField(default=list)),
                ('verified', models.BooleanField(default=False)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('payout_info', models.CharField(blank=True, max_length=100, null=True)),
                ('docs', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
