# Generated by Django 5.2.7 on 2025-10-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('users', '0002_privider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Privider',
            new_name='Provider',
        ),
    ]
