# Generated by Django 5.2.7 on 2025-12-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_privider_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('service_provider', 'Service Provider'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
