# Generated by Django 5.2.7 on 2025-12-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='docs',
            field=models.ImageField(blank=True, null=True, upload_to='provider_docs/'),
        ),
    ]
