# Generated by Django 5.2.7 on 2025-10-27 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('users', '0003_rename_privider_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service_type', models.CharField(max_length=50)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('availability', models.TextField(blank=True, null=True)),
                ('contact_method', models.CharField(choices=[('phone', 'Phone'), ('message', 'Message'), ('booking_link', 'Booking Link')], default='phone', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.provider')),
            ],
        ),
    ]
