# Generated by Django 5.2.7 on 2025-12-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='provider_id',
            new_name='provider',
        ),
    ]
