# Generated by Django 5.2.7 on 2025-12-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contact_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
